import {
  useEffect,
  useRef,
  useState,
  type CSSProperties,
  type ReactNode,
} from "react";
import { createPortal } from "react-dom";
import {
  Check,
  CheckCircle2,
  Clock3,
  CreditCard,
  ExternalLink,
  Globe2,
  Info,
  Landmark,
  LockKeyhole,
  QrCode,
  RefreshCcw,
  ShieldCheck,
  Smartphone,
  TriangleAlert,
  WalletCards,
  X,
} from "lucide-react";

export type CheckoutCurrency = "INR" | "USD";
export type CheckoutItemKind = "live" | "video";
export type CheckoutStatus = "idle" | "pending" | "unknown" | "paid" | "failed";
export type PaymentMethod = "card" | "paypal" | "upi" | "qr";

export interface CheckoutItem {
  id: string;
  kind: CheckoutItemKind;
  title: string;
  instructor: string;
  /** Student price in major currency units. */
  price: number;
  startsAt?: string;
  duration?: string;
  thumbnailUrl?: string;
}

export interface CheckoutPreviewProps {
  open: boolean;
  item: CheckoutItem | null;
  currency: CheckoutCurrency;
  /** ISO 3166-1 alpha-2 code. UPI is enabled only for IN. */
  countryCode?: string;
  status?: CheckoutStatus;
  paymentReference?: string;
  providerName?: string;
  qrExpiresInSeconds?: number;
  onClose: () => void;
  /**
   * Starts a provider-hosted checkout. This component never collects card,
   * bank, PayPal, UPI, or identity details.
   */
  onContinue?: (method: PaymentMethod) => void | Promise<void>;
  /** Re-checks an ambiguous provider status without creating another charge. */
  onCheckStatus?: () => void | Promise<void>;
}

const NEON = "#00FFB2";
const VIOLET = "#8B83FF";
const GOLD = "#FFCB66";
const PINK = "#FF5F7D";
const PANEL = "#090911";
const SOFT = "#A8A8BC";

const paymentMethods: Array<{
  id: PaymentMethod;
  label: string;
  detail: string;
  icon: typeof CreditCard;
}> = [
  {
    id: "card",
    label: "Card",
    detail: "Credit or debit card on the provider page",
    icon: CreditCard,
  },
  {
    id: "paypal",
    label: "PayPal",
    detail: "Continue to PayPal to approve payment",
    icon: WalletCards,
  },
  {
    id: "upi",
    label: "UPI",
    detail: "Use a supported UPI app or UPI ID",
    icon: Smartphone,
  },
  {
    id: "qr",
    label: "Provider QR",
    detail: "Time-limited QR generated by the payment provider",
    icon: QrCode,
  },
];

function money(amount: number, currency: CheckoutCurrency) {
  return new Intl.NumberFormat(currency === "INR" ? "en-IN" : "en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: currency === "INR" ? 0 : 2,
    maximumFractionDigits: currency === "INR" ? 0 : 2,
  }).format(amount);
}

function timeLeft(totalSeconds: number) {
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return String(minutes).padStart(2, "0") + ":" + String(seconds).padStart(2, "0");
}

function Badge({
  children,
  color,
}: {
  children: ReactNode;
  color: string;
}) {
  return (
    <span
      className="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[9px] font-black uppercase tracking-[0.14em]"
      style={{
        color,
        background: color + "12",
        borderColor: color + "35",
      }}
    >
      <span
        aria-hidden="true"
        className="h-1.5 w-1.5 rounded-full"
        style={{ background: color, boxShadow: "0 0 8px " + color }}
      />
      {children}
    </span>
  );
}

function StatusNotice({
  status,
  reference,
  providerName,
  checking,
  onCheck,
}: {
  status: CheckoutStatus;
  reference?: string;
  providerName: string;
  checking: boolean;
  onCheck?: () => void;
}) {
  if (status === "idle") return null;

  const config = {
    pending: {
      color: GOLD,
      icon: Clock3,
      title: "Payment is still pending",
      copy:
        providerName +
        " has not confirmed a final result yet. Do not pay again while this payment is being checked.",
    },
    unknown: {
      color: PINK,
      icon: TriangleAlert,
      title: "Payment status is unknown",
      copy:
        "The provider response was interrupted. Check this payment instead of starting a second checkout.",
    },
    paid: {
      color: NEON,
      icon: CheckCircle2,
      title: "Payment confirmed",
      copy: "The provider has confirmed this payment. Your access can now be activated.",
    },
    failed: {
      color: PINK,
      icon: TriangleAlert,
      title: "Payment was not completed",
      copy:
        "No successful charge is confirmed. Check the provider reference before trying another checkout.",
    },
  }[status];

  const Icon = config.icon;
  const canCheck = status === "pending" || status === "unknown" || status === "failed";

  return (
    <div
      className="mb-5 rounded-2xl border p-4"
      style={{
        background: config.color + "0A",
        borderColor: config.color + "30",
      }}
      role="status"
      aria-live="polite"
    >
      <div className="flex items-start gap-3">
        <div
          className="flex h-9 w-9 flex-none items-center justify-center rounded-xl border"
          style={{
            color: config.color,
            background: config.color + "10",
            borderColor: config.color + "30",
          }}
        >
          <Icon size={17} aria-hidden="true" />
        </div>
        <div className="min-w-0 flex-1">
          <p className="text-sm font-black text-[#F5F5FF]">{config.title}</p>
          <p className="mt-1 text-xs leading-5" style={{ color: SOFT }}>
            {config.copy}
          </p>
          {reference && (
            <p className="mt-2 font-mono text-[10px]" style={{ color: config.color }}>
              Reference: {reference}
            </p>
          )}
        </div>
      </div>
      {canCheck && onCheck && (
        <button
          type="button"
          onClick={onCheck}
          disabled={checking}
          className="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border px-4 text-xs font-black transition hover:bg-white/[0.03] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#00FFB2] disabled:cursor-wait disabled:opacity-60"
          style={{ color: config.color, borderColor: config.color + "35" }}
        >
          <RefreshCcw
            size={13}
            aria-hidden="true"
            className={checking ? "animate-spin" : ""}
          />
          {checking ? "Checking provider…" : "Check payment status"}
        </button>
      )}
    </div>
  );
}

function ProviderQrPreview({
  remaining,
  onRefresh,
}: {
  remaining: number;
  onRefresh: () => void;
}) {
  const expired = remaining <= 0;

  return (
    <div
      className="mt-4 rounded-2xl border p-4"
      style={{
        background: VIOLET + "08",
        borderColor: expired ? PINK + "35" : VIOLET + "30",
      }}
    >
      <div className="flex items-center gap-4">
        <div
          aria-hidden="true"
          className="relative flex h-24 w-24 flex-none items-center justify-center overflow-hidden rounded-xl border"
          style={{
            borderColor: "rgba(255,255,255,0.12)",
            background:
              "repeating-conic-gradient(#D9D7FF 0% 25%, #171721 0% 50%) 50% / 12px 12px",
            opacity: expired ? 0.35 : 0.72,
          }}
        >
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#090911]">
            <LockKeyhole size={17} style={{ color: VIOLET }} />
          </div>
        </div>
        <div className="min-w-0">
          <Badge color={expired ? PINK : VIOLET}>
            {expired ? "Preview expired" : "Expires in " + timeLeft(remaining)}
          </Badge>
          <p className="mt-3 text-xs font-bold text-[#EEEEF8]">
            Provider QR preview
          </p>
          <p className="mt-1 text-[11px] leading-5" style={{ color: SOFT }}>
            This pattern is intentionally not scannable. A real QR must come
            directly from the payment provider.
          </p>
        </div>
      </div>
      {expired && (
        <button
          type="button"
          onClick={onRefresh}
          className="mt-3 flex min-h-10 w-full items-center justify-center gap-2 rounded-xl border border-white/10 text-xs font-black text-[#EDEDF7] transition hover:bg-white/[0.03] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#8B83FF]"
        >
          <RefreshCcw size={13} aria-hidden="true" />
          Refresh preview timer
        </button>
      )}
    </div>
  );
}

export function CheckoutPreview({
  open,
  item,
  currency,
  countryCode = currency === "INR" ? "IN" : "US",
  status = "idle",
  paymentReference,
  providerName = "the payment provider",
  qrExpiresInSeconds = 300,
  onClose,
  onContinue,
  onCheckStatus,
}: CheckoutPreviewProps) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const [method, setMethod] = useState<PaymentMethod>(
    countryCode.toUpperCase() === "IN" ? "upi" : "card",
  );
  const [remaining, setRemaining] = useState(qrExpiresInSeconds);
  const [starting, setStarting] = useState(false);
  const [checking, setChecking] = useState(false);

  const isIndia = countryCode.toUpperCase() === "IN";

  useEffect(() => {
    if (!open) return;
    setMethod(isIndia ? "upi" : "card");
    setRemaining(qrExpiresInSeconds);
    setStarting(false);
    setChecking(false);
  }, [open, item?.id, isIndia, qrExpiresInSeconds]);

  useEffect(() => {
    if (!open || method !== "qr" || remaining <= 0) return;
    const timer = window.setInterval(() => {
      setRemaining((value) => Math.max(0, value - 1));
    }, 1000);
    return () => window.clearInterval(timer);
  }, [open, method, remaining]);

  useEffect(() => {
    if (!open) return;

    const previousFocus = document.activeElement as HTMLElement | null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    window.requestAnimationFrame(() => dialogRef.current?.focus());

    const handleKeyDown = (event: globalThis.KeyboardEvent) => {
      if (event.key === "Escape") {
        event.preventDefault();
        onClose();
        return;
      }

      if (event.key !== "Tab" || !dialogRef.current) return;

      const focusable = Array.from(
        dialogRef.current.querySelectorAll<HTMLElement>(
          'button:not([disabled]), input:not([disabled]), [href], [tabindex]:not([tabindex="-1"])',
        ),
      ).filter((element) => element.offsetParent !== null);

      if (focusable.length === 0) {
        event.preventDefault();
        dialogRef.current.focus();
        return;
      }

      const first = focusable[0];
      const last = focusable[focusable.length - 1];
      if (event.shiftKey && document.activeElement === first) {
        event.preventDefault();
        last.focus();
      } else if (!event.shiftKey && document.activeElement === last) {
        event.preventDefault();
        first.focus();
      }
    };

    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      document.body.style.overflow = previousOverflow;
      previousFocus?.focus();
    };
  }, [open, onClose]);

  if (!open || !item || typeof document === "undefined") return null;

  const total = item.price;
  const selectedMethod = paymentMethods.find((entry) => entry.id === method);
  const canStart =
    status === "idle" &&
    Boolean(onContinue) &&
    !(method === "upi" && !isIndia) &&
    !(method === "qr" && remaining <= 0);

  const continueToProvider = async () => {
    if (!onContinue || !canStart) return;
    setStarting(true);
    try {
      await onContinue(method);
    } finally {
      setStarting(false);
    }
  };

  const checkStatus = onCheckStatus
    ? async () => {
        setChecking(true);
        try {
          await onCheckStatus();
        } finally {
          setChecking(false);
        }
      }
    : undefined;

  const modal = (
    <div
      className="fixed inset-0 z-[100] flex items-end justify-center bg-black/80 p-0 backdrop-blur-md sm:items-center sm:p-5"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
    >
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="checkout-preview-title"
        aria-describedby="checkout-preview-description"
        tabIndex={-1}
        className="relative max-h-[94vh] w-full overflow-y-auto rounded-t-[28px] border border-white/[0.09] text-[#F5F5FF] outline-none sm:max-w-5xl sm:rounded-[28px] sm:focus-visible:ring-2 sm:focus-visible:ring-[#00FFB2]/40"
        style={{
          background:
            "radial-gradient(circle at 10% 0%, rgba(0,255,178,0.07), transparent 26%), radial-gradient(circle at 90% 0%, rgba(139,131,255,0.09), transparent 28%), #050509",
          boxShadow: "0 40px 120px rgba(0,0,0,0.7)",
        }}
      >
        <header className="sticky top-0 z-10 flex items-start gap-4 border-b border-white/[0.07] bg-[#050509]/95 px-5 py-5 backdrop-blur-xl sm:px-7">
          {item.thumbnailUrl && (
            <img
              src={item.thumbnailUrl}
              alt=""
              className="h-14 w-20 flex-none rounded-xl object-cover"
            />
          )}
          <div className="min-w-0 flex-1">
            <div className="mb-2 flex flex-wrap items-center gap-2">
              <Badge color={item.kind === "live" ? PINK : VIOLET}>
                {item.kind === "live" ? "Live class" : "On-demand video"}
              </Badge>
              <span className="text-[10px] font-bold uppercase tracking-[0.12em]" style={{ color: SOFT }}>
                Preview checkout
              </span>
            </div>
            <h2 id="checkout-preview-title" className="truncate text-xl font-black sm:text-2xl">
              {item.title}
            </h2>
            <p id="checkout-preview-description" className="mt-1 text-xs" style={{ color: SOFT }}>
              with {item.instructor}
              {item.startsAt ? " · " + item.startsAt : ""}
              {item.duration ? " · " + item.duration : ""}
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close checkout preview"
            className="flex h-10 w-10 flex-none items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.025] text-[#D7D7E3] transition hover:bg-white/[0.06] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#00FFB2]"
          >
            <X size={17} aria-hidden="true" />
          </button>
        </header>

        <div className="grid gap-6 p-5 sm:p-7 lg:grid-cols-[1.08fr_0.92fr]">
          <section aria-labelledby="payment-method-heading">
            <StatusNotice
              status={status}
              reference={paymentReference}
              providerName={providerName}
              checking={checking}
              onCheck={checkStatus}
            />

            <div className="mb-5 flex items-start gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4">
              <Globe2 className="mt-0.5 flex-none" size={17} style={{ color: NEON }} aria-hidden="true" />
              <div>
                <p className="text-xs font-black text-[#EEEEF8]">
                  {isIndia ? "India checkout" : "International checkout"} · {currency}
                </p>
                <p className="mt-1 text-[11px] leading-5" style={{ color: SOFT }}>
                  Available methods and final settlement depend on your country and the connected provider.
                </p>
              </div>
            </div>

            <fieldset disabled={status !== "idle" || starting}>
              <legend id="payment-method-heading" className="mb-3 text-sm font-black">
                Choose a secure payment method
              </legend>
              <div className="grid gap-3 sm:grid-cols-2">
                {paymentMethods.map((entry) => {
                  const disabled = entry.id === "upi" && !isIndia;
                  const selected = method === entry.id;
                  const Icon = entry.icon;

                  return (
                    <label
                      key={entry.id}
                      className="relative flex min-h-[104px] cursor-pointer items-start gap-3 rounded-2xl border p-4 transition"
                      style={{
                        background: selected ? NEON + "08" : PANEL,
                        borderColor: selected ? NEON + "38" : "rgba(255,255,255,0.075)",
                        opacity: disabled ? 0.45 : 1,
                        cursor: disabled ? "not-allowed" : "pointer",
                      }}
                    >
                      <input
                        type="radio"
                        name="checkout-method"
                        value={entry.id}
                        checked={selected}
                        disabled={disabled}
                        onChange={() => setMethod(entry.id)}
                        className="sr-only"
                      />
                      <span
                        className="flex h-10 w-10 flex-none items-center justify-center rounded-xl border"
                        style={{
                          color: selected ? NEON : "#9292A6",
                          background: selected ? NEON + "10" : "rgba(255,255,255,0.025)",
                          borderColor: selected ? NEON + "30" : "rgba(255,255,255,0.08)",
                        }}
                      >
                        <Icon size={18} aria-hidden="true" />
                      </span>
                      <span className="min-w-0">
                        <span className="flex items-center gap-2 text-sm font-black text-[#F0F0FA]">
                          {entry.label}
                          {selected && <Check size={13} style={{ color: NEON }} aria-hidden="true" />}
                        </span>
                        <span className="mt-1 block text-[11px] leading-5" style={{ color: SOFT }}>
                          {disabled ? "Available only for India checkout" : entry.detail}
                        </span>
                      </span>
                    </label>
                  );
                })}
              </div>
            </fieldset>

            {method === "qr" && (
              <ProviderQrPreview
                remaining={remaining}
                onRefresh={() => setRemaining(qrExpiresInSeconds)}
              />
            )}

            <div
              className="mt-5 flex items-start gap-3 rounded-2xl border p-4"
              style={{ background: NEON + "07", borderColor: NEON + "22" }}
            >
              <ShieldCheck className="mt-0.5 flex-none" size={17} style={{ color: NEON }} aria-hidden="true" />
              <div>
                <p className="text-xs font-black text-[#E7FFF7]">No financial data is collected here.</p>
                <p className="mt-1 text-[11px] leading-5" style={{ color: SOFT }}>
                  Card, PayPal, UPI, QR, and bank details belong on the provider-hosted page. Groovly should receive only signed payment status and a reference.
                </p>
              </div>
            </div>
          </section>

          <aside aria-labelledby="order-summary-heading">
            <div
              className="rounded-2xl border p-5 sm:p-6"
              style={{
                background: PANEL,
                borderColor: "rgba(255,255,255,0.08)",
                boxShadow: "0 24px 70px rgba(0,0,0,0.25)",
              }}
            >
              <div className="flex items-center justify-between gap-3">
                <h3 id="order-summary-heading" className="text-lg font-black">
                  Order summary
                </h3>
                <Landmark size={18} style={{ color: VIOLET }} aria-hidden="true" />
              </div>

              <dl className="mt-5 space-y-3 text-sm">
                <div className="flex items-center justify-between gap-4 rounded-xl bg-white/[0.025] px-4 py-3">
                  <dt style={{ color: SOFT }}>
                    {item.kind === "live" ? "Live class" : "Video price"}
                  </dt>
                  <dd className="font-black">{money(item.price, currency)}</dd>
                </div>
                {item.kind === "video" && (
                  <div className="flex items-center justify-between gap-4 rounded-xl bg-white/[0.025] px-4 py-3">
                    <dt style={{ color: SOFT }}>Creator settlement fee (not added to total)</dt>
                    <dd className="font-black">{currency === "INR" ? "−₹30" : "−₹30 equivalent"}</dd>
                  </div>
                )}
                <div
                  className="flex items-center justify-between gap-4 rounded-xl border px-4 py-4"
                  style={{ background: NEON + "08", borderColor: NEON + "25" }}
                >
                  <dt className="font-black">Total</dt>
                  <dd className="text-xl font-black" style={{ color: NEON }}>
                    {money(total, currency)}
                  </dd>
                </div>
              </dl>

              {item.kind === "live" ? (
                <div
                  className="mt-5 rounded-2xl border p-4"
                  style={{ background: VIOLET + "08", borderColor: VIOLET + "28" }}
                >
                  <div className="flex items-start gap-3">
                    <LockKeyhole className="mt-0.5 flex-none" size={17} style={{ color: VIOLET }} aria-hidden="true" />
                    <div>
                      <p className="text-xs font-black text-[#EFEEFF]">
                        Live payment is held until completion
                      </p>
                      <p className="mt-1 text-[11px] leading-5" style={{ color: SOFT }}>
                        The provider confirms the charge, Groovly marks it Held, and funds release after the class is completed and the safety window closes.
                      </p>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="mt-5 flex items-start gap-3 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4">
                  <Info className="mt-0.5 flex-none" size={15} style={{ color: GOLD }} aria-hidden="true" />
                  <p className="text-[11px] leading-5" style={{ color: SOFT }}>
                    The ₹30 platform fee is deducted from the creator settlement for each completed on-demand video sale; it is not added to the student total. Provider fees or taxes, when applicable, must be disclosed before confirmation.
                  </p>
                </div>
              )}

              <button
                type="button"
                onClick={continueToProvider}
                disabled={!canStart || starting}
                className="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl px-5 text-sm font-black text-black transition hover:-translate-y-0.5 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#00FFB2] active:translate-y-0 disabled:cursor-not-allowed disabled:opacity-50"
                style={{ background: NEON }}
              >
                {starting ? (
                  <>
                    <RefreshCcw className="animate-spin" size={14} aria-hidden="true" />
                    Opening provider…
                  </>
                ) : (
                  <>
                    Preview {selectedMethod?.label || "provider"} handoff
                    <ExternalLink size={14} aria-hidden="true" />
                  </>
                )}
              </button>
              <p className="mt-2 text-center text-[10px] font-black uppercase tracking-[0.12em]" style={{ color: SOFT }}>
                {onContinue
                  ? "Preview connected · no details entered here"
                  : "Preview only · provider handoff not connected"}
              </p>

              {(status === "pending" || status === "unknown") && (
                <div className="mt-4 flex items-start gap-2 rounded-xl border border-white/[0.07] bg-black/20 p-3">
                  <TriangleAlert className="mt-0.5 flex-none" size={13} style={{ color: GOLD }} aria-hidden="true" />
                  <p className="text-[10px] leading-5" style={{ color: SOFT }}>
                    Never create a second checkout while a payment is pending or unknown. Use Check payment status with the existing reference.
                  </p>
                </div>
              )}
            </div>
          </aside>
        </div>
      </div>
    </div>
  );

  return createPortal(modal, document.body);
}

export default CheckoutPreview;
